### ISSUE TITLE
Sous-Chefs Cookbook setup

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/prometheus#1]
Cookbook needs setting up for sous

- metadata
- terraform (admin)
- standard files (bot)
- cookstyle (bot)
- labels standardise (bot)
- github actions
- circleci (admin)
- rebase the files used.

**Comment by Xorima** [comment]
So the cookbook is now in terraform, all the things labelled (bot) will happen automatically over the next 24 hours

**Comment by mbaitelman** [comment]
Looks like it didn't run.

**Comment by Xorima** [comment]
Appears like the bot doesn't understand forks, I have asked github support to unfork this repo for now anyway

**Comment by mbaitelman** [comment]
I think it's unforked.

**Comment by Xorima** [comment]
Sweet, I asked GH support to do that for us :D

**Comment by mbaitelman** [comment]
@xorimabot has done its thing. 
Closing as complete.
